/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  EthereumZamaGatewayConfig,
  EthereumZamaGatewayConfigInterface,
} from "../../../../fhevm/config/ZamaGatewayConfig.sol/EthereumZamaGatewayConfig";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f80fd5b507f93ab6e17f2c461cce6ea5d4ec117e51dda77a64affc2b2c05f8cd440def0e70080546001600160a01b0319169055603e8060495f395ff3fe60806040525f80fdfea2646970667358221220d45f3b27f435cf71209680e0591afe326df1ef55f6e5d2806668033d4df8511264736f6c63430008180033";

type EthereumZamaGatewayConfigConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EthereumZamaGatewayConfigConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EthereumZamaGatewayConfig__factory extends ContractFactory {
  constructor(...args: EthereumZamaGatewayConfigConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      EthereumZamaGatewayConfig & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): EthereumZamaGatewayConfig__factory {
    return super.connect(runner) as EthereumZamaGatewayConfig__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EthereumZamaGatewayConfigInterface {
    return new Interface(_abi) as EthereumZamaGatewayConfigInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): EthereumZamaGatewayConfig {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as EthereumZamaGatewayConfig;
  }
}
