/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EthereumZamaGatewayConfig__factory } from "./EthereumZamaGatewayConfig__factory";
export { SepoliaZamaGatewayConfig__factory } from "./SepoliaZamaGatewayConfig__factory";
