/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  SepoliaZamaGatewayConfig,
  SepoliaZamaGatewayConfigInterface,
} from "../../../../fhevm/config/ZamaGatewayConfig.sol/SepoliaZamaGatewayConfig";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f80fd5b507f93ab6e17f2c461cce6ea5d4ec117e51dda77a64affc2b2c05f8cd440def0e70080546001600160a01b0319167333347831500f1e73f0cccbb95c9f86b94d7b1123179055603e80605f5f395ff3fe60806040525f80fdfea26469706673582212204c51b8bcc423aba2ef6c62b907769b93facdb7fc095d3fdfa69bed9f71a4ca8064736f6c63430008180033";

type SepoliaZamaGatewayConfigConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SepoliaZamaGatewayConfigConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SepoliaZamaGatewayConfig__factory extends ContractFactory {
  constructor(...args: SepoliaZamaGatewayConfigConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SepoliaZamaGatewayConfig & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): SepoliaZamaGatewayConfig__factory {
    return super.connect(runner) as SepoliaZamaGatewayConfig__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SepoliaZamaGatewayConfigInterface {
    return new Interface(_abi) as SepoliaZamaGatewayConfigInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SepoliaZamaGatewayConfig {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as SepoliaZamaGatewayConfig;
  }
}
