/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialStrategyAgentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PARAM_APY_TARGET"
      | "PARAM_EVAL_COUNT"
      | "PARAM_LIQUIDATION_BUFFER"
      | "PARAM_MAX_LEVERAGE"
      | "PARAM_REBALANCE_THRESHOLD"
      | "PARAM_STOP_LOSS_BUFFER"
      | "authorizeAgent"
      | "authorizedAgents"
      | "callbackEvaluationReveal"
      | "callbackParameterReveal"
      | "createStrategy"
      | "deactivateStrategy"
      | "evaluateStrategy"
      | "getOwnerStrategies"
      | "getStrategyMetadata"
      | "nextStrategyId"
      | "pendingReveals"
      | "protocolOwner"
      | "requestEvaluationReveal"
      | "requestParameterReveal"
      | "updateStrategy"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentAuthorized"
      | "EvaluationPerformed"
      | "EvaluationRevealed"
      | "ParameterRevealed"
      | "RevealRequested"
      | "StrategyCreated"
      | "StrategyDeactivated"
      | "StrategyUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PARAM_APY_TARGET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PARAM_EVAL_COUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PARAM_LIQUIDATION_BUFFER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PARAM_MAX_LEVERAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PARAM_REBALANCE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PARAM_STOP_LOSS_BUFFER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeAgent",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedAgents",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackEvaluationReveal",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackParameterReveal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createStrategy",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateStrategy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "evaluateStrategy",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerStrategies",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStrategyMetadata",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextStrategyId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingReveals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestEvaluationReveal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestParameterReveal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStrategy",
    values: [
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "PARAM_APY_TARGET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PARAM_EVAL_COUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PARAM_LIQUIDATION_BUFFER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PARAM_MAX_LEVERAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PARAM_REBALANCE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PARAM_STOP_LOSS_BUFFER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackEvaluationReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackParameterReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evaluateStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerStrategies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStrategyMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextStrategyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingReveals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestEvaluationReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestParameterReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStrategy",
    data: BytesLike
  ): Result;
}

export namespace AgentAuthorizedEvent {
  export type InputTuple = [agent: AddressLike, status: boolean];
  export type OutputTuple = [agent: string, status: boolean];
  export interface OutputObject {
    agent: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvaluationPerformedEvent {
  export type InputTuple = [
    strategyId: BigNumberish,
    blockNumber: BigNumberish
  ];
  export type OutputTuple = [strategyId: bigint, blockNumber: bigint];
  export interface OutputObject {
    strategyId: bigint;
    blockNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvaluationRevealedEvent {
  export type InputTuple = [
    strategyId: BigNumberish,
    shouldRebalance: boolean,
    stopLossHit: boolean
  ];
  export type OutputTuple = [
    strategyId: bigint,
    shouldRebalance: boolean,
    stopLossHit: boolean
  ];
  export interface OutputObject {
    strategyId: bigint;
    shouldRebalance: boolean;
    stopLossHit: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParameterRevealedEvent {
  export type InputTuple = [
    strategyId: BigNumberish,
    paramType: BigNumberish,
    revealedValue: BigNumberish
  ];
  export type OutputTuple = [
    strategyId: bigint,
    paramType: bigint,
    revealedValue: bigint
  ];
  export interface OutputObject {
    strategyId: bigint;
    paramType: bigint;
    revealedValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevealRequestedEvent {
  export type InputTuple = [
    strategyId: BigNumberish,
    paramType: BigNumberish,
    requestId: BigNumberish
  ];
  export type OutputTuple = [
    strategyId: bigint,
    paramType: bigint,
    requestId: bigint
  ];
  export interface OutputObject {
    strategyId: bigint;
    paramType: bigint;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyCreatedEvent {
  export type InputTuple = [strategyId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [strategyId: bigint, owner: string];
  export interface OutputObject {
    strategyId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyDeactivatedEvent {
  export type InputTuple = [strategyId: BigNumberish];
  export type OutputTuple = [strategyId: bigint];
  export interface OutputObject {
    strategyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyUpdatedEvent {
  export type InputTuple = [strategyId: BigNumberish];
  export type OutputTuple = [strategyId: bigint];
  export interface OutputObject {
    strategyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialStrategyAgent extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialStrategyAgent;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialStrategyAgentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PARAM_APY_TARGET: TypedContractMethod<[], [bigint], "view">;

  PARAM_EVAL_COUNT: TypedContractMethod<[], [bigint], "view">;

  PARAM_LIQUIDATION_BUFFER: TypedContractMethod<[], [bigint], "view">;

  PARAM_MAX_LEVERAGE: TypedContractMethod<[], [bigint], "view">;

  PARAM_REBALANCE_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  PARAM_STOP_LOSS_BUFFER: TypedContractMethod<[], [bigint], "view">;

  authorizeAgent: TypedContractMethod<
    [agent: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  authorizedAgents: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  callbackEvaluationReveal: TypedContractMethod<
    [
      requestId: BigNumberish,
      shouldRebalanceRaw: BigNumberish,
      stopLossRaw: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  callbackParameterReveal: TypedContractMethod<
    [requestId: BigNumberish, revealedValue: BigNumberish],
    [void],
    "nonpayable"
  >;

  createStrategy: TypedContractMethod<
    [
      encApyTarget: BytesLike,
      encRebalanceThreshold: BytesLike,
      encStopLossBuffer: BytesLike,
      encLiquidationBuffer: BytesLike,
      encMaxLeverage: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  deactivateStrategy: TypedContractMethod<
    [strategyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  evaluateStrategy: TypedContractMethod<
    [
      strategyId: BigNumberish,
      encCurrentApy: BytesLike,
      encCurrentHealth: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getOwnerStrategies: TypedContractMethod<
    [owner: AddressLike],
    [bigint[]],
    "view"
  >;

  getStrategyMetadata: TypedContractMethod<
    [strategyId: BigNumberish],
    [
      [
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        owner: string;
        isActive: boolean;
        createdAt: bigint;
        lastEvaluatedAt: bigint;
        apyTargetHandle: bigint;
        rebalanceThresholdHandle: bigint;
        stopLossBufferHandle: bigint;
        liquidationBufferHandle: bigint;
        maxLeverageHandle: bigint;
        evaluationCountHandle: bigint;
      }
    ],
    "view"
  >;

  nextStrategyId: TypedContractMethod<[], [bigint], "view">;

  pendingReveals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint] & {
        strategyId: bigint;
        requester: string;
        paramType: bigint;
      }
    ],
    "view"
  >;

  protocolOwner: TypedContractMethod<[], [string], "view">;

  requestEvaluationReveal: TypedContractMethod<
    [strategyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestParameterReveal: TypedContractMethod<
    [strategyId: BigNumberish, paramType: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateStrategy: TypedContractMethod<
    [
      strategyId: BigNumberish,
      encApyTarget: BytesLike,
      encRebalanceThreshold: BytesLike,
      encStopLossBuffer: BytesLike,
      encLiquidationBuffer: BytesLike,
      encMaxLeverage: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PARAM_APY_TARGET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PARAM_EVAL_COUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PARAM_LIQUIDATION_BUFFER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PARAM_MAX_LEVERAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PARAM_REBALANCE_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PARAM_STOP_LOSS_BUFFER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "authorizeAgent"
  ): TypedContractMethod<
    [agent: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedAgents"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "callbackEvaluationReveal"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      shouldRebalanceRaw: BigNumberish,
      stopLossRaw: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callbackParameterReveal"
  ): TypedContractMethod<
    [requestId: BigNumberish, revealedValue: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createStrategy"
  ): TypedContractMethod<
    [
      encApyTarget: BytesLike,
      encRebalanceThreshold: BytesLike,
      encStopLossBuffer: BytesLike,
      encLiquidationBuffer: BytesLike,
      encMaxLeverage: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateStrategy"
  ): TypedContractMethod<[strategyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "evaluateStrategy"
  ): TypedContractMethod<
    [
      strategyId: BigNumberish,
      encCurrentApy: BytesLike,
      encCurrentHealth: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getOwnerStrategies"
  ): TypedContractMethod<[owner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getStrategyMetadata"
  ): TypedContractMethod<
    [strategyId: BigNumberish],
    [
      [
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        owner: string;
        isActive: boolean;
        createdAt: bigint;
        lastEvaluatedAt: bigint;
        apyTargetHandle: bigint;
        rebalanceThresholdHandle: bigint;
        stopLossBufferHandle: bigint;
        liquidationBufferHandle: bigint;
        maxLeverageHandle: bigint;
        evaluationCountHandle: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextStrategyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingReveals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint] & {
        strategyId: bigint;
        requester: string;
        paramType: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestEvaluationReveal"
  ): TypedContractMethod<[strategyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestParameterReveal"
  ): TypedContractMethod<
    [strategyId: BigNumberish, paramType: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateStrategy"
  ): TypedContractMethod<
    [
      strategyId: BigNumberish,
      encApyTarget: BytesLike,
      encRebalanceThreshold: BytesLike,
      encStopLossBuffer: BytesLike,
      encLiquidationBuffer: BytesLike,
      encMaxLeverage: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentAuthorized"
  ): TypedContractEvent<
    AgentAuthorizedEvent.InputTuple,
    AgentAuthorizedEvent.OutputTuple,
    AgentAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "EvaluationPerformed"
  ): TypedContractEvent<
    EvaluationPerformedEvent.InputTuple,
    EvaluationPerformedEvent.OutputTuple,
    EvaluationPerformedEvent.OutputObject
  >;
  getEvent(
    key: "EvaluationRevealed"
  ): TypedContractEvent<
    EvaluationRevealedEvent.InputTuple,
    EvaluationRevealedEvent.OutputTuple,
    EvaluationRevealedEvent.OutputObject
  >;
  getEvent(
    key: "ParameterRevealed"
  ): TypedContractEvent<
    ParameterRevealedEvent.InputTuple,
    ParameterRevealedEvent.OutputTuple,
    ParameterRevealedEvent.OutputObject
  >;
  getEvent(
    key: "RevealRequested"
  ): TypedContractEvent<
    RevealRequestedEvent.InputTuple,
    RevealRequestedEvent.OutputTuple,
    RevealRequestedEvent.OutputObject
  >;
  getEvent(
    key: "StrategyCreated"
  ): TypedContractEvent<
    StrategyCreatedEvent.InputTuple,
    StrategyCreatedEvent.OutputTuple,
    StrategyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "StrategyDeactivated"
  ): TypedContractEvent<
    StrategyDeactivatedEvent.InputTuple,
    StrategyDeactivatedEvent.OutputTuple,
    StrategyDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "StrategyUpdated"
  ): TypedContractEvent<
    StrategyUpdatedEvent.InputTuple,
    StrategyUpdatedEvent.OutputTuple,
    StrategyUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentAuthorized(address,bool)": TypedContractEvent<
      AgentAuthorizedEvent.InputTuple,
      AgentAuthorizedEvent.OutputTuple,
      AgentAuthorizedEvent.OutputObject
    >;
    AgentAuthorized: TypedContractEvent<
      AgentAuthorizedEvent.InputTuple,
      AgentAuthorizedEvent.OutputTuple,
      AgentAuthorizedEvent.OutputObject
    >;

    "EvaluationPerformed(uint256,uint256)": TypedContractEvent<
      EvaluationPerformedEvent.InputTuple,
      EvaluationPerformedEvent.OutputTuple,
      EvaluationPerformedEvent.OutputObject
    >;
    EvaluationPerformed: TypedContractEvent<
      EvaluationPerformedEvent.InputTuple,
      EvaluationPerformedEvent.OutputTuple,
      EvaluationPerformedEvent.OutputObject
    >;

    "EvaluationRevealed(uint256,bool,bool)": TypedContractEvent<
      EvaluationRevealedEvent.InputTuple,
      EvaluationRevealedEvent.OutputTuple,
      EvaluationRevealedEvent.OutputObject
    >;
    EvaluationRevealed: TypedContractEvent<
      EvaluationRevealedEvent.InputTuple,
      EvaluationRevealedEvent.OutputTuple,
      EvaluationRevealedEvent.OutputObject
    >;

    "ParameterRevealed(uint256,uint8,uint64)": TypedContractEvent<
      ParameterRevealedEvent.InputTuple,
      ParameterRevealedEvent.OutputTuple,
      ParameterRevealedEvent.OutputObject
    >;
    ParameterRevealed: TypedContractEvent<
      ParameterRevealedEvent.InputTuple,
      ParameterRevealedEvent.OutputTuple,
      ParameterRevealedEvent.OutputObject
    >;

    "RevealRequested(uint256,uint8,uint256)": TypedContractEvent<
      RevealRequestedEvent.InputTuple,
      RevealRequestedEvent.OutputTuple,
      RevealRequestedEvent.OutputObject
    >;
    RevealRequested: TypedContractEvent<
      RevealRequestedEvent.InputTuple,
      RevealRequestedEvent.OutputTuple,
      RevealRequestedEvent.OutputObject
    >;

    "StrategyCreated(uint256,address)": TypedContractEvent<
      StrategyCreatedEvent.InputTuple,
      StrategyCreatedEvent.OutputTuple,
      StrategyCreatedEvent.OutputObject
    >;
    StrategyCreated: TypedContractEvent<
      StrategyCreatedEvent.InputTuple,
      StrategyCreatedEvent.OutputTuple,
      StrategyCreatedEvent.OutputObject
    >;

    "StrategyDeactivated(uint256)": TypedContractEvent<
      StrategyDeactivatedEvent.InputTuple,
      StrategyDeactivatedEvent.OutputTuple,
      StrategyDeactivatedEvent.OutputObject
    >;
    StrategyDeactivated: TypedContractEvent<
      StrategyDeactivatedEvent.InputTuple,
      StrategyDeactivatedEvent.OutputTuple,
      StrategyDeactivatedEvent.OutputObject
    >;

    "StrategyUpdated(uint256)": TypedContractEvent<
      StrategyUpdatedEvent.InputTuple,
      StrategyUpdatedEvent.OutputTuple,
      StrategyUpdatedEvent.OutputObject
    >;
    StrategyUpdated: TypedContractEvent<
      StrategyUpdatedEvent.InputTuple,
      StrategyUpdatedEvent.OutputTuple,
      StrategyUpdatedEvent.OutputObject
    >;
  };
}
