/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as zamaFhevmConfigSol from "./ZamaFHEVMConfig.sol";
export type { zamaFhevmConfigSol };
import type * as zamaGatewayConfigSol from "./ZamaGatewayConfig.sol";
export type { zamaGatewayConfigSol };
