/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EthereumZamaGatewayConfig } from "./EthereumZamaGatewayConfig";
export type { SepoliaZamaGatewayConfig } from "./SepoliaZamaGatewayConfig";
